'\" -*- coding: UTF-8 -*-
.\" Man page for alts
.\"
.\" Copyright ©2023 SUSE LLC
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"    http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.pc
.TH ALTS 1 "2021-07-07" "1.0.0" "libalternatives"

.SH NAME
alts - manages preferred default commands

.SH SYNOPSIS
alts [options]

.SH DESCRIPTION

alts is a default program manager and its aim is to provide an alternative to the update-alternatives
system without relying on symlinks. Instead of symlinks, it relies on configuration files. This allows
for a simple per-system or per-user override of the default configuration.

.SH OPTIONS

    alts -h         --- this help screen
    alts -l[name]   --- list programs or just one with given name
    alts [-u] [-s] -n <program> [-p <alt_priority>]
       sets an override with a given priority as default
       if priority is not set, then resets to default by removing override
       -u -- user override, default for non-root users
       -s -- system override, default for root users
       -n -- program to override with a given priority alternative


.SH SEE ALSO
update-alternatives(1)

.
